sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t traviscibuiltimage -f Dockerfile.dev .
script:
  - docker run -e CI=true traviscibuiltimage npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-955674382099"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
