sudo: required
language: generic

services:
  -docker

before_install:
  - docker build -t travisbuiltdockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true travisbuiltdockerreact npm run test -- --coverage
